"""empty message

Revision ID: 3890087d3aa1
Revises: 
Create Date: 2023-12-19 11:01:09.934459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3890087d3aa1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('faculty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faculty', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
